name: test-all

on: [push]

jobs:
  linux-macos:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - name: py3.9-verbose
            python-version: 3.9
            os: ubuntu-latest
            env: 
              # make sure that the most verbose level is not crashy
              PARAMSURVEY_VERBOSE: 3
              PYTEST_STDERR_VISIBLE: -s
          - name: py3.10-noray
            python-version: '3.10'
            os: ubuntu-latest
            env:
              # no ray wheel yet on 3.10
              ONLY_BUILTINS: 1
          - name: macos-3.9-noray
            python-version: 3.9
            os: macos-latest
            env:
              # no ray on macos
              ONLY_BUILTINS: 1

    environment: paramsurvey-test

    steps:

    - uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip --use-feature=in-tree-build install . .[test]
        echo ONLY_BUILTINS is $ONLY_BUILTINS
        if [ -z "$ONLY_BUILTINS" ]; then
          pip --use-feature=in-tree-build install .[ray]
        fi

    - name: 'pytest'
      run: |
        make test_coverage

    - name: 'coveralls'
      run: |
        pip install coveralls
        coveralls
      env:
        CIRCLECI: 1
        CIRCLE_BRANCH: ${{ env.GITHUB_REF_NAME }}
        CIRCLE_BUILD_NUM: ${{ env.GITHUB_RUN_NUMBER }}
        # github -> settings -> environments -> paramsurvey-test 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
